# Configuration file used by the pipeline hydration step
# to render the manifests for the different environments
releaseName: &name renovate
namespace: *name
environments:
  local:
    apis: &apis
    - external-secrets.io/v1/ExternalSecret
    - monitoring.coreos.com/v1/ServiceMonitor
    valueFiles:
    - values-subchart-overrides.yaml
    - values-local.yaml
  sf-k8s01-dev: &devEnvironment
    apis: *apis
    valueFiles:
    - values-subchart-overrides.yaml
    - values-development.yaml
  sf-k8s02-dev: *devEnvironment
  sf-k8s01-prod:
    apis: *apis
    valueFiles:
    - values-subchart-overrides.yaml
    - values-production.yaml
