local:
  apis: &apis
  - external-secrets.io/v1beta1/ExternalSecret
  valueFiles:
  - values-subchart-overrides.yaml
  - values-local.yaml
sf-k8s01-dev: &environment
  apis: *apis
  valueFiles:
  - values-subchart-overrides.yaml
  - values-development.yaml
sf-k8s02-dev: *environment
sf-k8s01-prod:
  apis: *apis
  valueFiles:
  - values-subchart-overrides.yaml
  - values-production.yaml
