renovate:
 # sub chart values
  image:
    registry: harbor.k8s01.steadforce.com
    repository: steadops/renovate
    tag: "36.81"

  cronjob:
    activeDeadlineSeconds: 1200
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 2
    jobRestartPolicy: Never
    schedule: '13 */1 * * *'
    successfulJobsHistoryLimit: 1
    jobBackoffLimit: 3

  redis:
    enabled: true
    global:
      storageClass: "nfs1"
    master:
      persistence:
        size: 100Mi
      resources:
        limits:
          cpu: 300m
          memory: 48Mi
        requests:
          cpu: 15m
          memory: 24Mi
    replica:
      persistence:
        size: 100Mi
      resources:
        limits:
          cpu: 300m
          memory: 48Mi
        requests:
          cpu: 15m
          memory: 24Mi
    architecture: replication
  resources:
    limits:
     cpu: 1000m
     memory: 768Mi
    requests:
     cpu: 600m
     memory: 512Mi

  env:
    GITHUB_COM_TOKEN: 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

  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://gitea.devcloud01.intern.steadforce.com/api/v1",
        "token": "194436a9434ea91db4692379cbe0b04525dc9607",
        "autodiscover": false,
        "onboardingConfig": {"extends": ["config:base", ":dependencyDashboard"]},
        "allowedPostUpgradeCommands": [ "^echo apply custom helm file filters$" ],
        "repositories": [ "steadforce-applications/vertical-pod-autoscaler", "steadforce-applications/strimzi-operator"],
        "packageRules": [
         {
           "matchManagers": [ 'helmv3' ],
             "postUpgradeTasks": {
               "commands": [ "echo apply custom helm file filters" ],
               "fileFilters": [
                 "charts/*.tgz"
               ]
            }
         },
         {
            matchDatasources: [ 'pypi' ],
            matchUpdateTypes: [ 'minor', 'patch' ],
            groupName: '{{manager}} dependencies non-major',
            groupSlug: 'dependencies-non-major',
            additionalBranchPrefix: '{{manager}}-'
        }
        ]
      }
