global:
  stage: local
renovate:
  # sub chart values
  cronjob:
    schedule: '*/1 * * * *'

  env:
    LOG_LEVEL: debug

  resources:
    limits:
     cpu: 0m
    requests:
     cpu: 0m
     memory: 0Mi

valkey:
  replica:
    enabled: false
  resources:
    limits:
      cpu: 0m
    requests:
      cpu: 0m
      memory: 0Mi
  dataStorage:
    enabled: true
    requestedSize: 100Mi
    className: nfs1
  metrics:
    exporter:
      resources:
        limits:
          cpu: 0m
        requests:
          cpu: 0m
          memory: 0Mi
