renovate:
  cronjob:
    activeDeadlineSeconds: 1200
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 2
    jobBackoffLimit: 3
    jobRestartPolicy: Never
    schedule: '13 */1 * * *'
    successfulJobsHistoryLimit: 1

  env:
    RENOVATE_REDIS_URL: redis://renovate-valkey

  resources:
    limits:
     cpu: 1000m
     memory: 768Mi
    requests:
     cpu: 600m
     memory: 512Mi

  renovate:
    config: |
      {
         "autodiscover": true,
         "onboardingConfig": {
           "$schema": "https://docs.renovatebot.com/renovate-schema.json",
           "extends": [
             "config:recommended",
             ":dependencyDashboard"
           ],
           "postUpdateOptions": [
             "helmUpdateSubChartArchives"
           ]
         },
         "packageRules": [
           {
             "matchDatasources": [
               "pypi"
             ],
             "matchUpdateTypes": [
               "minor",
               "patch"
             ],
             "groupName": "{{manager}} dependencies non-major",
             "groupSlug": "dependencies-non-major",
             "additionalBranchPrefix": "{{manager}}-"
           }
         ]
      }
  envFrom:
  - secretRef:
      name: renovate-environment
  extraObjects:
  - |
    {{- if .Capabilities.APIVersions.Has "external-secrets.io/v1/ExternalSecret" }}
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: &name renovate-environment
    spec:
      dataFrom:
      - extract:
          key: /{{ .Values.global.stage }}/renovate/gitea
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: awssm-parameter-store
      target:
        name: *name
    {{- end }}

valkey:
  replica:
    enabled: true
    replicas: 3
    persistence:
      size: 100Mi
      storageClass: nfs1
  resources:
    limits:
      cpu: 300m
      memory: 48Mi
    requests:
      cpu: 15m
      memory: 24Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      extraLabels:
        prometheus: cluster-monitoring
    exporter:
      resources:
        limits:
          cpu: 100m
          memory: 48Mi
        requests:
          cpu: 5m
          memory: 24Mi
