global:
  stage: production
renovate:
  resources:
    limits:
     cpu: 1500m
     memory: 1536Mi
    requests:
     memory: 768Mi
  redis:
    master:
      resources:
        limits:
          memory: 64Mi
        requests:
          memory: 48Mi
    replica:
      resources:
        limits:
          memory: 64Mi
        requests:
          memory: 48Mi
