global:
  stage: local
renovate:
  # sub chart values
  cronjob:
    schedule: '*/1 * * * *'

  env:
    LOG_LEVEL: debug

  redis:
    architecture: standalone
    master:
      resources:
        limits: {}
        requests: {}
    replica:
      resources:
        limits: {}
        requests: {}
  resources:
    limits:
     cpu: 0m
    requests:
     cpu: 0m
     memory: 0Mi
