---
# Source: renovate/charts/renovate/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
  labels:
    helm.sh/chart: renovate-46.317.1
    app.kubernetes.io/name: renovate
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "44.111.3"
    app.kubernetes.io/managed-by: Helm
data:
  config.json: |-
    {
       "autodiscover": true,
       "onboardingConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": [
           "config:recommended",
           ":dependencyDashboard"
         ],
         "postUpdateOptions": [
           "helmUpdateSubChartArchives"
         ]
       },
       "packageRules": [
         {
           "matchDatasources": [
             "pypi"
           ],
           "matchUpdateTypes": [
             "minor",
             "patch"
           ],
           "groupName": "{{manager}} dependencies non-major",
           "groupSlug": "dependencies-non-major",
           "additionalBranchPrefix": "{{manager}}-"
         }
       ]
    }
