---
# Source: renovate/charts/renovate/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
  labels:
    helm.sh/chart: renovate-40.62.1
    app.kubernetes.io/name: renovate
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "40.62.1"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: renovate
        app.kubernetes.io/instance: renovate
    spec:
      activeDeadlineSeconds: 1200
      backoffLimit: 3
      template:
        metadata:
          labels:
            app.kubernetes.io/name: renovate
            app.kubernetes.io/instance: renovate
        spec:
          serviceAccountName: default
          restartPolicy: Never
          containers:
            - name: renovate
              image: "ghcr.io/renovatebot/renovate:40.62.1"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: config-volume
                  mountPath: /usr/src/app/config.json
                  subPath: config.json
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: /usr/src/app/config.json
                - name: RENOVATE_REDIS_URL
                  value: redis://renovate-redis-master
                - name: "LOG_LEVEL"
                  value: "debug"
              envFrom:
                - secretRef:
                    name: renovate-environment
              resources:
                limits:
                  cpu: 0m
                  memory: 768Mi
                requests:
                  cpu: 0m
                  memory: 0Mi
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
