---
# Source: renovate/charts/renovate/templates/extra-manifests.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name renovate-environment
spec:
  dataFrom:
    - extract:
        key: /production/renovate/gitea
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: awssm-parameter-store
  target:
    name: *name
