---
# Source: renovate/charts/valkey/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-valkey
  labels:
    helm.sh/chart: valkey-0.12.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs1
