---
# Source: renovate/charts/valkey/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate-valkey
  labels:
    helm.sh/chart: valkey-0.12.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
