---
# Source: renovate/charts/valkey/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: renovate-valkey
  labels:
    helm.sh/chart: valkey-0.12.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    statefulset.kubernetes.io/pod-name: renovate-valkey-0
