---
# Source: renovate/charts/valkey/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: renovate-valkey
  labels:
    helm.sh/chart: valkey-0.12.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: valkey
    app.kubernetes.io/component: service-monitor
    prometheus: cluster-monitoring
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - renovate
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: renovate
      app.kubernetes.io/component: metrics
