---
# Source: renovate/charts/valkey/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: renovate-valkey-headless
  labels:
    helm.sh/chart: valkey-0.12.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp
      port: 6379
      targetPort: tcp
      protocol: TCP
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
