---
# Source: renovate/charts/valkey/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: renovate-valkey
  labels:
    helm.sh/chart: valkey-0.12.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: renovate-valkey-headless
  replicas: 4
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: renovate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: valkey-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "nfs1"
        resources:
          requests:
            storage: "100Mi"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/instance: renovate
      annotations:
        checksum/initconfig: "287be78d8cad4753569dd71decf0fe4a"
        checksum/config: "351408a5511a2fc356c435fd0bccaafd"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: renovate-valkey
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: renovate-valkey-init
          image: docker.io/valkey/valkey:9.1.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          command: ["/scripts/init.sh"]
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          volumeMounts:
            - name: valkey-data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
            - name: valkey-config
              mountPath: /usr/local/etc/valkey/valkey.conf
              subPath: valkey.conf
      containers:
        - name: renovate-valkey
          image: docker.io/valkey/valkey:9.1.2
          imagePullPolicy: IfNotPresent
          command: ["valkey-server"]
          args: ["/data/conf/valkey.conf"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: VALKEY_LOG_LEVEL
              value: "notice"
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            exec:
              command:
                - valkey-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 96Mi
          volumeMounts:
            - name: valkey-data
              mountPath: /data
        - name: metrics
          image: ghcr.io/oliver006/redis_exporter:v1.79.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: metrics
              containerPort: 9121
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            limits:
              cpu: 250m
              memory: 48Mi
            requests:
              cpu: 5m
              memory: 24Mi
          env:
            - name: REDIS_ALIAS
              value: renovate-valkey
      volumes:
        - name: scripts
          configMap:
            name: renovate-valkey-init-scripts
            defaultMode: 0555
        - name: valkey-config
          configMap:
            name: renovate-valkey-config
