name: Helm hydration

on:
  push:
    branches:
    - main

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      hydrations: ${{ steps.hydrations.outputs.hydrations }}
    steps:
    - uses: actions/checkout@v5
    - name: Define hydrations
      id: hydrations
      run: |
        echo "hydrations=$(yq 'keys | to_json(0)' helm-config.yaml)" >> "$GITHUB_OUTPUT"
  get-renovate-subchart-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.renovate_subchart_version.outputs.version }}
    steps:
    - uses: actions/checkout@v5
    - name: Get renovate subchart version
      id: renovate_subchart_version
      run: |
        DEP_NAME=$(yq '.name' Chart.yaml)
        echo "version=$(DEP_NAME=$DEP_NAME yq 'explode( . ) | .dependencies[] | select(.name == strenv(DEP_NAME)).version' Chart.yaml)" >> "$GITHUB_OUTPUT"
  hydrate-chart:
    runs-on: ubuntu-latest
    needs:
    - define-matrix
    - get-renovate-subchart-version
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        hydration: ${{ fromJSON(needs.define-matrix.outputs.hydrations) }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Helm
      uses: azure/setup-helm@v4.3.1
    - name: Update Helm dependencies
      run: |
        helm dependency update
    - name: Hydrate
      env:
        hydration: ${{ matrix.hydration }}
      run: |
        RELEASE_NAME=renovate
        helm template \
          -a "$(hydration=$hydration yq '.[env(hydration)].apis | @csv' helm-config.yaml)" \
          -f "$(hydration=$hydration yq '.[env(hydration)].valueFiles | @csv' helm-config.yaml)" \
          -n $RELEASE_NAME \
          --output-dir hydrated-manifests \
          --include-crds \
          --release-name $RELEASE_NAME \
          --skip-tests \
          .
          DEP_NAME=$(yq '.name' Chart.yaml)
          if [ ! -d "hydrated-manifests/$RELEASE_NAME/$RELEASE_NAME" ]; then
            mv -v hydrated-manifests/$RELEASE_NAME/$DEP_NAME hydrated-manifests/$RELEASE_NAME/$RELEASE_NAME
          fi
    - name: Create pull request
      if: ${{ !env.ACT }}
      uses: peter-evans/create-pull-request@v7
      with:
        base: environments/${{ matrix.hydration }}
        branch: hydration-pull-request/${{ matrix.hydration }}-${{ needs.get-renovate-subchart-version.outputs.version }}
        title: Hydrated manifests for environment ${{ matrix.hydration }} for renovate subchart version ${{ needs.get-renovate-subchart-version.outputs.version }}
